# Mars Crater Analysis

This Jupyter notebook contains codes for analyisng the Mars Crater Dataset, and it's a part through getting started with Data Analyis Course on Coursera.

## Importing modules and dataset.

In [1]:
##importing modules: pandas and numpy alongside the mars crater dataset
import pandas as pd
import numpy as np

data = pd.read_csv("marscrater_pds.csv", low_memory=False)

## Assigning selected columns to variables.

### Frequency distributions for our three key variables:

**DIAM_CIRCLE_IMAGE** (diameter — binned into ranges)

In [9]:
diam_freq = pd.cut(data['DIAM_CIRCLE_IMAGE'], bins=10)
diam_table = diam_freq.value_counts().sort_index().reset_index()
diam_table.columns = ['Diameter Range (km)', 'Count']
diam_table

   Diameter Range (km)   Count
0    (-0.163, 117.322]  384160
1   (117.322, 233.644]     148
2   (233.644, 349.966]      24
3   (349.966, 466.288]       6
4    (466.288, 582.61]       2
5    (582.61, 698.932]       1
6   (698.932, 815.254]       0
7   (815.254, 931.576]       0
8  (931.576, 1047.898]       0
9  (1047.898, 1164.22]       2

**DEPTH_RIMFLOOR_TOPOG** (depth — binned)

In [11]:
depth_freq = pd.cut(data['DEPTH_RIMFLOOR_TOPOG'], bins=10)
depth_table = depth_freq.value_counts().sort_index().reset_index()
depth_table.columns = ['Depth Range (km)', 'Count']
depth_table

  Depth Range (km)   Count
0  (-0.425, 0.117]  325454
1   (0.117, 0.654]   45769
2   (0.654, 1.191]   10194
3   (1.191, 1.728]    2191
4   (1.728, 2.265]     599
5   (2.265, 2.802]     108
6   (2.802, 3.339]      20
7   (3.339, 3.876]       4
8   (3.876, 4.413]       1
9    (4.413, 4.95]       3

**MORPHOLOGY_EJECTA_1** (ejecta type — categorical counts)

In [14]:
morph_table = data['MORPHOLOGY_EJECTA_1'].value_counts(dropna=False).reset_index()
morph_table.columns = ['Ejecta Morphology', 'Count']
morph_table

diam_table['Percentage (%)'] = (diam_table['Count'] / diam_table['Count'].sum() * 100).round(2)
diam_table

   Diameter Range (km)   Count  Percentage (%)
0    (-0.163, 117.322]  384160           99.95
1   (117.322, 233.644]     148            0.04
2   (233.644, 349.966]      24            0.01
3   (349.966, 466.288]       6            0.00
4    (466.288, 582.61]       2            0.00
5    (582.61, 698.932]       1            0.00
6   (698.932, 815.254]       0            0.00
7   (815.254, 931.576]       0            0.00
8  (931.576, 1047.898]       0            0.00
9  (1047.898, 1164.22]       2            0.00

## What we did & what the output tells us
### What we did:

We ran a **frequency distribution**, a count of how often values appear across three variables. For continous numeric variables (diameter & depth), we grouped vaules into **10 equal width bins**. For the categorical variables (morphology), we counted each unique text label directly.

**Conclusion**: Also **heavily right-skewed**. Most craters are very shallow, many with depth = 0.0, meaning depth was **never measured** (missing data). Deep craters are rare. This is important: depth data is **incomplete** and that will affect any analysis we do relating diameter to depth.

**MORPHOLOGY_EJECTA_1 (Ejecta Type)**
The output shows very small proportions (e.g., 0.000260 = 0.026%) for the visible categories, and 156 unique morphology types exist.

→ **Conclusion:** Most craters have no recorded morphology (blank/NaN). Among those that do, ejecta types are spread across many rare categories. This means the categorical variable is sparse and dominated by missing values, which limits how much we can generalize about ejecta patterns.

## Overall Conclusions to Draw
**Small craters dominate Mars**: the size distribution is log-normal/power-law shaped, not uniform.

**Depth data is largely missing**: working with depth requires filtering out unmeasured craters (depth > 0).

**Ejecta morphology is rarely recorded**: it can only be meaningfully analyzed on a subset of the dataset.

**All three variables are non-normally distributed**: statistical methods that assume normality (like basic regression) should be applied with caution.

These insights should directly inform our next step: **choosing appropriate statistical tests and deciding whether to subset the data before deeper analysis.**